# Generated by Django 3.2.13 on 2022-06-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_custom_access_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custom_Access_Token',
            new_name='CustomAccessToken',
        ),
    ]
